### ISSUE TITLE
Would you planning to make the Pytorch version for this code ?

### ISSUE THREAD

**Issue by Johnson-yue** [sjenni/dfgan#2]
Hi, the Tensorflow is so difficult to read and write , so  do you have a plan to provide a pytorch version for this code ??

**Comment by Johnson-yue** [comment]
Hi @sjenni  I re-implement pytorch version.  Would you add repo in your ReadMe file:https://github.com/Johnson-yue/pytorch-DFGAN  ?

**Comment by sjenni** [comment]
Hi @Johnson-yue! Thanks for the info and re-implementation. I updated the ReadMe.
